routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/{lang?}', 'HomeController@welcome')->name('welcome');
Route::get('/news/{slung}/{lang?}', 'HomeController@news')->name('news');
Route::get('/blog/{lang?}', 'BlogController@blog')->name('blog');
Route::get('/blog/{slung}/{lang?}', 'BlogController@singlePost')->name('blogPost');
Route::get('/tags/{slung}/{lang?}', 'HomeController@tags')->name('tags');
Route::get('/category/{slung}/{lang?}', 'HomeController@category')->name('category');
Route::get('/gallery/{lang?}', 'HomeController@gallery')->name('gallery');
Route::get('/gallery/{slung}/{lang?}', 'HomeController@imageGallery')->name('image-gallery');
Route::get('/video/{lang?}', 'HomeController@videoGallery')->name('video');
Route::get('/appointment/{lang?}', 'HomeController@appointment')->name('appointment');
Route::get('/contact/{lang?}', 'HomeController@contact')->name('contact');
Route::get('/search/{lang?}', 'HomeController@search')->name('search');
Route::get('/blogsearch/{lang?}', 'BlogController@search')->name('bsearch');

Auth::routes(['verify' => true]);


Route::get('/language/{lang?}', 'HomeController@chnageLanguage')->name('language');

// Email
Route::get('mail/send/{lang?}', 'MailController@send')->name('mail/send');

// login 
Route::get('login/{lang?}', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');

//logout 
Route::get('logout/{lang?}', 'Auth\LoginController@logout')->name('logout');
//Route::get('password/email/{lang?}', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');

//Register
Route::get('register/{lang?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register')->name('register.post');
Route::get('password/reset/{token?}/{lang?}', 'Auth\ResetPasswordController@showResetForm');
Route::get('/clear-cache/{lang?}', function() {
    $exitCode = Artisan::call('cache:clear');
     return 'what you want';
});

//Route::post('login', 'Auth\LoginController@login')->name('login.post');
//Route::post('logout', 'Auth\LoginController@logout')->name('logout.post');
//Route::post('register', 'Auth\RegisterController@register')->name('register.post');
//Route::get('password/email/{lang?}', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.email');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
//Route::post('password/reset', 'Auth\ForgotPasswordController@reset');
//Route::post('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
 
Route::group(['prefix'=>'admin'], function (){    
        Route::group(['prefix'=>'{lang?}'], function (){       
                Route::get('/', 'Admin\HomeController@index')->name('home');
                Route::get('/profile', 'Admin\HomeController@profile')->name('profile');
                Route::get('/newspublished', 'Admin\NewsController@published')->name('newsPublished');
                Route::get('/rejectednews', 'Admin\NewsController@rejectedNews')->name('newsRejected');
                
                Route::resource('category', 'Admin\CategoryController');
                Route::resource('news', 'Admin\NewsController');
                Route::resource('tags', 'Admin\TagsController');
                Route::resource('blogcategory', 'Admin\BlogCategoryController');
                Route::resource('blogpost', 'Admin\BlogPostController');
                Route::resource('blogtags', 'Admin\BlogTagsController');
                Route::resource('notices', 'Admin\NoticeController');
                Route::resource('division', 'Admin\DivisionController');
                Route::resource('district', 'Admin\DistrictController');
                Route::resource('upozila', 'Admin\UpozilaController');
                Route::resource('module', 'Admin\ModuleController');
                Route::resource('user', 'Admin\UserController');
                Route::resource('usergroup', 'Admin\UserGroupController');
                Route::resource('userpermission', 'Admin\UserPermissionController');
                Route::resource('useractivities', 'Admin\UserActivitiesController');
                Route::resource('designation', 'Admin\DesignationController');
                
                Route::get('/userpermission_bulk_add', 'Admin\UserPermissionController@bulkAdd');
                Route::post('/userpermission_bulk_add', 'Admin\UserPermissionController@bulkAddPost')->name('admin_permission_bulkpost');
                Route::patch('/changePasswordAdmin/{id}', 'Admin\HomeController@changePasswordAdmin')->name('admin_change_pass');
               
                
                Route::get('/appointment', 'Admin\NoticeController@appointment')->name('admin_appointment');
                Route::post('/appointment', 'Admin\NoticeController@appointmentUpdate')->name('admin_appointment');
                
                Route::get('/settings', 'Admin\SettingsController@addBlock')->name('admin_addblock');
                Route::post('/settings', 'Admin\SettingsController@addBlockUpdate')->name('admin_addblock');
                
                Route::get('/aboutus', 'Admin\SettingsController@aboutUs')->name('aboutus');
                Route::post('/aboutus', 'Admin\SettingsController@aboutUsUpdate')->name('aboutus');
                
                Route::get('/newsajax', 'Admin\NewsController@ajaxCreate')->name('admin_ajax');
                Route::post('/newsajaxupload', 'Admin\NewsController@ajaxUpdate')->name('admin_upload');
                
                Route::get('/contact', 'Admin\ContactController@index')->name('admin_contact');
                Route::post('/contact', 'Admin\ContactController@update')->name('admin_contact');
                
                Route::get('/ajaxshow/{id}', 'Admin\NewsController@ajaxShow')->name('admin_news_show');
                
                //crooper js
                Route::get('/crooperjs', 'Admin\HomeController@CrooperJsGet')->name('crooper');
                Route::post('/crooperjs', 'Admin\HomeController@crooperJsPost')->name('crooper');
                
        });
});

Auth::routes(['verify' => true]);

resources/views/admin/croop.blade.php
@extends('admin.layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            {{$title_bd}}
            <small>যোগ করুন</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href=""><i class="fa fa-dashboard"></i> ড্যাশবোর্ড</a></li>
            <li><a href="#">নতুন  যোগ </a></li>
            <li class="active">{{$title_bd}}</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <div class="row">
                            <div class="col-md-6">
                                <h3 class="box-title">
                                    @if($errors->any())
                                    <ul class="alert alert-danger">
                                        @foreach($errors->all() as $error)
                                        <li> {{$error}} </li>
                                        @endforeach
                                    </ul>
                                    @endif
                                    {!!Session::get('success')!!}
                                </h3>
                            </div>
                            <div class="col-md-6 text-right text-bold">
                                <a href="{{ route('crooper',['lang'=>'bd']) }}">
                                    <button class="btn btn-primary btn-flat" type="button">
                                        <i class="fa fa-eye" aria-hidden="true"></i> তালিকা  দেখুন
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form id="tryitForm" role="form" data-toggle="validator"  class='form-horizontal' method="post" action="{{ route('crooper',['lang'=>'bd']) }}" enctype="multipart/form-data">
                            @csrf
                            <div class="box-body">
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Large modal</button>

                                
                                <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                                    <div class="modal-dialog modal-lg" role="document">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span></button>
                                                  <h4 class="modal-title">Default Modal</h4>
                                                </div>
                                                <div class="modal-body">
                                                        <div class="image-wrapper" id="image-4-wrapper">
                                                               <input id="imageUpload" name="browseImg" type="file"><br>
                                                               <img id="image-2" src="/storage/images/croop/test.jpg">
                                                               <div>
                                                                       <input id="width" type="text">
                                                                       <input id="height" type="text">
                                                                       <input id="x" type="text">
                                                                       <input id="y" type="text">
                                                               </div>
                                                        </div>
                                                </div>
                                                <div class="modal-footer">
                                                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                                                  <button type="button" class="btn btn-primary">Save changes</button>
                                                </div>
                                      </div>
                                    </div>
                                  </div>
                                
                                
                                
                                
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer text-right">
                                <input id="status" type="hidden" name="status" value="1">
                                <button id="draft" data-status="1" class="btn btn-default btn-flat" type="submit">
                                    <i class="fa fa-save" aria-hidden="true"></i>
                                    ড্রাফট হিসেবে  সংরক্ষণ করুন
                                </button>
                                <button id="save" data-status="2" class="btn btn-primary btn-flat" type="submit">
                                    <i class="fa fa-save" aria-hidden="true"></i>
                                    সংরক্ষণ করুন
                                </button>
                            </div>
                            <!-- /.box-footer -->
                        </form>

                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@endsection

resources/views/admin/croopp_not sure.blade.php
@extends('admin.layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            {{$title_bd}}
            <small>যোগ করুন</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href=""><i class="fa fa-dashboard"></i> ড্যাশবোর্ড</a></li>
            <li><a href="#">নতুন  যোগ </a></li>
            <li class="active">{{$title_bd}}</li>
        </ol>
    </section>
            <div class="image-wrapper" id="image-4-wrapper">
                <img id="image-2" src="/storage/images/croop/testo.jpg">
                <form>
                    <div>
                        <label for="width">width:</label> 
                        <input id="width" type="text">
                    </div>
                    <div>
                        <label for="height">height:</label>  
                        <input id="height" type="text">
                    </div>
                    <div>
                        <label for="x">x:</label>  
                        <input id="x" type="text">
                    </div>
                    <div>
                        <label for="y">y:</label>  
                        <input id="y" type="text">
                    </div>
                    <input id="cancel" type="reset" value="cancel">
                    <input id="update" type="button" value="Apply">
                </form>
            </div>        
@endsection

resources/views/admin/profile.blade.php
@extends('admin.layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            {{$title_bd}}
            <small>যোগ করুন</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href=""><i class="fa fa-dashboard"></i> ড্যাশবোর্ড</a></li>
            <li><a href="#">নতুন  যোগ </a></li>
            <li class="active">{{$title_bd}}</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <div class="row">
                            <div class="col-md-6">
                                <h3 class="box-title">
                                    @if($errors->any())
                                    <ul class="alert alert-danger">
                                        @foreach($errors->all() as $error)
                                        <li> {{$error}} </li>
                                        @endforeach
                                    </ul>
                                    @endif
                                    {!!Session::get('success')!!}
                                </h3>
                            </div>
                            <div class="col-md-6 text-right text-bold">
                               <!-- <a href=" ">
                                    <button class="btn btn-primary btn-flat" type="button">
                                        <i class="fa fa-eye" aria-hidden="true"></i> তালিকা  দেখুন
                                    </button>
                                </a> -->
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form id="tryitForm" role="form" data-toggle="validator"  class='form-horizontal' method="post" action="{{ route('user.update',['lang'=>'bd', 'id'=>$show->id]) }}" enctype="multipart/form-data">
                            <input name="_method" type="hidden" value="PATCH">
                                 @csrf                                                                                                                                         
                            <div class="box-body">
                                
                                <div class="form-group">
                                    <label for="name" class="col-sm-2 control-label"> প্রোফাইল ছবি  </label>
                                    <div class="col-sm-9">
                                        <img src="{{'/storage/images/profilethumb/'.$show->profile_picture}}" style="height: 100px;"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="imageUpload" class="col-sm-2 control-label" > পরিবর্তন করুন চিত্র পরিবর্তন করুন</label>
                                    <div class="col-sm-5">
                                        <input  value="{{ $show->profile_picture }}"  type="hidden" name="image_upload_edit" id="imageUploadEn">
                                        <input type="file" name="feature_image_upload" id="imageUpload">
                                        <p class="help-block">Please upload an image here</p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="name" class="col-sm-2 control-label"> নাম  </label>
                                    <div class="col-sm-7">
                                        <input name="name" value="{{ Auth::user()->name }}" class="form-control" id="name" placeholder="" type="text" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="name" class="col-sm-2 control-label">ই-মেইল</label>
                                    <div class="col-sm-7">
                                        <input name="email" value="{{ Auth::user()->email }}" class="form-control" id="email" placeholder="" type="text" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="mobile" class="col-sm-2 control-label">মোবাইল</label>
                                    <div class="col-sm-7">
                                        <input name="mobile" value="{{ Auth::user()->mobile }}" class="form-control" id="mobile" placeholder="" type="text" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="office" class="col-sm-2 control-label"> অফিস </label>
                                    <div class="col-sm-7">
                                        <select name="office" id="office" class="form-control select2m" required>
                                             <option value="">নির্বাচন করুন....</option>
                                                @if (count($office) > 0)
                                                  @foreach($office as $row)
                                                       <option value="{{$row->id}}" @if($show->office == $row->id) selected @endif>{{$row->name_bd}}</option>
                                                  @endforeach
                                                @endif
                                        </select> 
                                    </div>
                                </div>    
                              
                                <div class="form-group">
                                    <label for="job_title" class="col-sm-2 control-label">  জব টাইটেল </label>
                                    <div class="col-sm-7">
                                        <select name="job_title" id="office" class="form-control select2m" required>
                                             <option value="">নির্বাচন করুন....</option>
                                                @if (count($designation) > 0)
                                                  @foreach($designation as $row)
                                                       <option value="{{$row->id}}" @if($show->job_title == $row->id) selected @endif>{{$row->name_bd}}</option>
                                                  @endforeach
                                                @endif
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                        <label for="division" class="col-sm-2 control-label">  বিভাগ </label>
                                        <div class="col-sm-7">
                                            <select name="division" id="division" class="form-control select2m" required>
                                             <option value="">নির্বাচন করুন....</option>
                                                @if (count($division) > 0)
                                                  @foreach($division as $row)
                                                       <option value="{{$row->id}}" @if($show->division == $row->id) selected @endif>{{$row->name_bd}}</option>
                                                  @endforeach
                                                @endif
                                        </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                        <label for="district" class="col-sm-2 control-label">  জেলা </label>
                                        <div class="col-sm-7">
                                            <select name="district" id="district" class="form-control select2m" required>
                                             <option value="">নির্বাচন করুন....</option>
                                                @if (count($district) > 0)
                                                  @foreach($district as $row)
                                                       <option value="{{$row->id}}" @if($show->district == $row->id) selected @endif>{{$row->name_bd}}</option>
                                                  @endforeach
                                                @endif
                                        </select>
                                        </div>
                                </div>
                                 <div class="form-group">
                                        <label for="thana" class="col-sm-2 control-label">  থানা </label>
                                        <div class="col-sm-7">
                                            <select name="thana" id="thana" class="form-control select2m" required>
                                             <option value="">নির্বাচন করুন....</option>
                                                @if (count($thana) > 0)
                                                  @foreach($thana as $row)
                                                       <option value="{{$row->id}}" @if($show->thana == $row->id) selected @endif>{{$row->name_bd}}</option>
                                                  @endforeach
                                                @endif
                                        </select>
                                        </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer text-right">
                                <button class="btn btn-primary btn-flat" type="submit">
                                    <i class="fa fa-save" aria-hidden="true"></i>
                                    সংরক্ষণ করুন
                                </button>
                            </div>
                            <!-- /.box-footer -->
                        </form>

                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@endsection